DROP TABLE IF EXISTS scores;
CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  seed TEXT NOT NULL,
  day_number INTEGER NOT NULL,
  player_name TEXT NOT NULL,
  score INTEGER NOT NULL,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_day_score ON scores(day_number, score DESC);
